/* ==========================================================================
   data.js — every word and every media path lives here.
   Edit freely: nothing in app.js needs to change when you edit this file.

   Chapter shape:
   {
     id: Number,
     cardTitle: String,       // shown on the dashboard card — must NOT spoil
     title: String,           // shown once the chapter is opened (usually
                               // the same as cardTitle — only Chapter 2 and
                               // Chapter 11 lean on cardTitle for mystery)
     type: "message" | "photo" | "song" | "delivery" | "surprise" | "reveal"
         | "bridge" | "memoryCoupon" | "diary" | "tiles" | "letter" | "final"
         | "storyJourney", // storyJourney is the deterministic story-stage
                            // architecture shared by Chapters 3 through 7
     unlockAt: ISO string (IST) — omit for a chapter that uses manualUnlock instead,
     manualUnlock: true        // optional — see js/unlocks.js; ignores unlockAt entirely
     content: { ...type-specific fields }
   }
   ========================================================================== */

const CHAPTERS = [
  {
    id: 1,
    cardTitle: "Happy 21st, Bebu ❤️",
    title: "Happy 21st, Bebu",
    type: "message",
    unlockAt: unlockTime(0, 0, 0),
    content: {
      eyebrow: "01",
      heading: "Happy 21st, Bebu ❤️",
      body: [
        "Today is about you.",
        "So I made you a little place filled with pieces of us.",
        "Memories. Little things. Things I love about you. And a few surprises.",
        "Come back here at 1:00 AM — there's a little present waiting for you.",
        "Until then, take your time. There's no rush.",
      ],
    },
  },

  {
    id: 2,
    cardTitle: "A Little Surprise",
    title: "A Little Surprise",
    type: "surprise",
    unlockAt: CONFIG.chapter2RevealTime,
    content: {
      lockedLine: "LOCKED",
      openLines: ["It's time. ❤️", "You've got a little something with you.", "Time to open it."],
      openButtonLabel: "I OPENED IT ❤️",
      wearLines: ["Put it on."],
      wearButtonLabel: "I'M WEARING IT",
      listenLine: "Now listen to this.",
      audioLabel: "VOICE NOTE",
      audioTitle: "For you",
      audioSrc: "assets/audio/pendent audio.mp3",
      goodnightLines: [
        "That's enough for tonight. ❤️",
        "Sleep well, birthday girl.",
        "There's more waiting for you in the morning.",
      ],
    },
  },

  {
    id: 3,
    cardTitle: "How It Started",
    title: "How It Started",
    type: "storyJourney",
    unlockAt: unlockTime(0, 12, 0),
    content: {
      eyebrow: "03",
      heading: "How It Started",
      states: [
        {
          // 0 — Opening
          visualType: "opening",
          lines: [
            "Every story has a moment you can point back to and say...",
            "Maybe it really started here.",
            "For us, I think we have one.",
          ],
          timestamp: { label: "MEMORY TIMESTAMP", date: "9 APRIL 2025", time: "1:27 AM" },
          action: "GO BACK WITH ME →",
        },
        {
          // 1 — Before the moment
          visualType: "fragments",
          lines: [
            "Before there was an “us,” there were just ordinary days.",
            "Fest work.",
            "Long work sessions.",
            "Random conversations.",
            "Being around each other without really knowing where any of it was going.",
            "And somewhere in all those ordinary moments...",
            "I started noticing you.",
            "Not because you were trying to be noticed.",
            "Almost the opposite.",
            "You were just being you.",
            "Loving.",
            "Playful.",
            "Cheerful.",
            "You had this way of making things feel lighter without even trying.",
            "And then there were the little things.",
          ],
          fragments: ["FEST WORK", "LONG WORK SESSIONS", "RANDOM CONVERSATIONS"],
          action: "ONE OF THOSE LITTLE THINGS →",
        },
        {
          // 2 — The cake / work session
          visualType: "photo",
          lines: [
            "One of those little moments happened during one of our fest work sessions.",
            "You casually got a cake for me.",
            "It wasn't some huge dramatic gesture.",
            "It was just something you did.",
            "And maybe that's exactly why I remember it.",
            "You didn't make a big deal out of it.",
            "But looking back, these were the things I started noticing.",
            "The little things.",
            "The things you did without trying to make them special.",
            "But somehow...",
            "They were.",
            "I don't think I knew it at the time.",
            "But I was beginning to notice how special you were.",
          ],
          image: "assets/images/worksession.jpg",
          imageAlt: "Fest work session",
          imageLabel: "FEST WORK SESSION",
          action: "BUT THIS WASN'T THE MOMENT WE COUNT →",
        },
        {
          // 3 — The real beginning
          visualType: "timestampStory",
          intro: ["But if you ask us where it actually started...", "I think we always come back to this."],
          timestamp: { date: "9 APRIL 2025", time: "1:27 AM" },
          lines: [
            "The moment we usually point to when we talk about how it started.",
            "One night.",
            "One moment.",
            "And neither of us knew what it was going to become.",
            "You sent me a reel.",
            "A slightly flirty one.",
            "And somehow, I managed to turn replying to one reel into a full-night mission.",
            "Because obviously, I couldn't just reply normally.",
            "I had to think about it.",
            "Then think about it again.",
            "Then think about whether my reply sounded too much.",
            "Or too little.",
            "Or too obvious.",
            "Basically, I was terrified of messing it up.",
            "So I took the entire night...",
            "...just to send you one simple text.",
            "One.",
            "Simple.",
            "Text.",
            "Looking back, it's honestly hilarious.",
            "You sent one flirty reel.",
            "And I treated the reply like I was making the most important decision of my life.",
            "But I think that's why I remember it so clearly.",
            "Because somewhere in all that overthinking...",
            "I realised I really, really cared about what you thought of me.",
          ],
          action: "AND THEN CAME ASHOK REDI →",
        },
        {
          // 4 — Ashok Redi
          visualType: "lines",
          lines: [
            "And then came the first time we went to Ashok Redi.",
            "We sat there for a long time.",
            "Talking about nothing in particular.",
            "Nothing extraordinary.",
            "But somehow, I remember that evening.",
            "I remember not really wanting the conversation to end.",
            "Maybe that's another thing I didn't understand at the time.",
            "I just liked being there with you.",
          ],
          action: "I HAD ONE JOB →",
        },
        {
          // 5 — The hug
          visualType: "hug",
          lines: ["On the way back, I had one very simple plan.", "Hug you goodbye.", "Simple enough, right?", "Except..."],
          beats: ["HUG YOU GOODBYE", "HANDSHAKE"],
          quoteIntro: "And immediately my brain went:",
          quote: "Bhai... hug karna chahiye tha.",
          closingBeat: "AWKWARD SIDE-HUG",
          closingLines: ["...and then basically ran.", "That was my smooth exit."],
          action: "AND THEN I PANICKED →",
        },
        {
          // 6 — The overthinking
          visualType: "thoughts",
          lines: ["For the rest of that night, my brain wouldn't let it go."],
          thoughts: ["Bhai hug bhi diya...", "Ab ye mere baare mein kya soch rahi hogi?", "Did I mess this up?"],
          closingLines: [
            "I was genuinely convinced I'd somehow messed everything up.",
            "Which is actually pretty funny to me now.",
            "Because I was sitting there worrying that I'd ruined something...",
            "...without realising I was already standing somewhere at the beginning of us.",
            "I had no idea what was coming next.",
            "But I knew I wanted there to be a next.",
          ],
          action: "LOOKING BACK →",
        },
        {
          // 7 — Final chapter 3 screen
          visualType: "final",
          lines: [
            "Maybe that's what I love most about how we started.",
            "We didn't know it was the beginning.",
            "We were just living it.",
            "And now...",
          ],
          timestampLine: "9 April 2025, 1:27 AM",
          closingLines: ["is a moment I'll always be glad happened.", "Because it led me to you.", "❤️"],
          action: "CONTINUE",
          isFinal: true,
        },
      ],
    },
  },

  {
    id: 4,
    cardTitle: "The One I Never Asked Back For",
    title: "The One I Never Asked Back For",
    type: "storyJourney",
    unlockAt: unlockTime(0, 12, 40),
    content: {
      eyebrow: "04",
      heading: "The One I Never Asked Back For",
      states: [
        {
          visualType: "festCard",
          lines: ["Let's go back to Apogee."],
          cardTitle: "APOGEE FEST",
          cardLoading: "MEMORY LOADING...",
          action: "LET'S GO BACK →",
        },
        {
          visualType: "lines",
          lines: [
            "This was Apogee.",
            "And somewhere around this time, something had started changing.",
            "But not in the way you might think.",
            "We weren't a thing.",
            "We weren't secretly living in some movie.",
            "We were just...",
            "starting to notice each other.",
            "Not romantically.",
            "At least, not in the way either of us had figured out yet.",
            "We just genuinely enjoyed each other's company.",
            "Being around you was easy.",
            "Talking to you was easy.",
            "And somehow, I kept finding myself wanting to be around you.",
            "Nothing dramatic.",
            "Just two people slowly becoming a little more important to each other without really noticing it.",
          ],
          action: "THERE WAS ONE PROBLEM →",
        },
        {
          visualType: "jacketPicker",
          lines: ["And then there were the jackets.", "I got a few.", "And somehow...", "you ended up keeping one."],
          jackets: ["JACKET 01", "JACKET 02", "JACKET 03"],
          revealLines: [
            { text: "THE ONE WITH MY NAME ON IT.", emphasis: true },
            "You kept that one.",
            "Which, technically...",
            "you were supposed to return.",
          ],
          action: "BUT YOU DIDN'T →",
        },
        {
          visualType: "lines",
          lines: [
            "You never returned it.",
            "And honestly?",
            "I never really wanted you to.",
            "Which is funny...",
            "Because we weren't even in a relationship.",
            "It was still my jacket.",
            "You technically had every reason to give it back.",
            "But somewhere in my head...",
            "I just hoped you'd keep it.",
            "I didn't really know why.",
            "I just liked the idea of you having it.",
          ],
          action: "WHY DID I FEEL THAT WAY? →",
        },
        {
          visualType: "lines",
          lines: [
            "Maybe because...",
            "Even then, without knowing what any of this would become...",
            "I wanted you to have a little piece of my world.",
            "Not because I had some grand plan.",
            "Not because I knew we'd end up together.",
            "I didn't.",
            "I just...",
            "somehow hoped that someday...",
            { text: "you'd have your right to keep it.", emphasis: true },
            "Looking back now...",
            "that's probably the part that gets me.",
            "Because I didn't know what we were becoming.",
            "But some small part of me...",
            "already didn't want everything between us to have an expiry date.",
          ],
          action: "SO HERE'S THE THING →",
        },
        {
          visualType: "lines",
          lines: [
            "Maybe that's why I never really cared that you never gave it back.",
            "You kept the jacket.",
            "And somehow...",
            "I think a part of me was always hoping you'd keep it.",
            "Funny how something so ordinary...",
            "can carry a feeling you don't understand until much later.",
            "Apogee.",
            "The jackets.",
            "You keeping the one with my name on it.",
            "And me secretly being completely okay with that.",
            "Some things don't need to be returned.",
            "❤️",
          ],
          action: "KEEP GOING →",
          isFinal: true,
        },
      ],
    },
  },

  {
    id: 5,
    cardTitle: "The Thing I Always Notice",
    title: "The Thing I Always Notice",
    type: "storyJourney",
    unlockAt: unlockTime(0, 13, 20),
    content: {
      eyebrow: "05",
      heading: "The Thing I Always Notice",
      states: [
        {
          visualType: "lines",
          lines: ["Okay.", "There's one thing about you I really like.", "Actually...", "One very specific thing."],
          action: "WHAT? 👀",
        },
        {
          visualType: "punchReveal",
          punchLine: "Your hair.",
          punchFollowup: "Obviously.",
          lines: [
            "But not just because it's your hair.",
            "I think it's the way it somehow manages to look like you.",
            "Especially when you put it up in those messy buns.",
          ],
          action: "THE MESSY BUN STORY →",
        },
        {
          visualType: "lines",
          lines: [
            "I don't know when I started noticing it.",
            "But somewhere along the way, your messy buns became one of those little things I genuinely love seeing.",
            "They're not carefully done — that's kind of the point.",
            "A few strands doing their own thing, somehow messy and somehow still completely you.",
            "They don't look like you tried. They just happen.",
            "And somehow, you still look ridiculously cute.",
            "I've seen you with your hair properly done, and yes, you look beautiful.",
            "But there's something about those random messy buns — the ones that look like you just tied your hair up and carried on with your day — that gets me every time.",
            "Maybe because it's one of those little versions of you that I don't think you even realise I notice.",
          ],
          action: "SHOW ME THE PROOF →",
        },
        {
          visualType: "photo",
          lines: ["Okay...", "Exhibit A."],
          image: "assets/images/YOUR MESSY BUN.jpg",
          imageAlt: "Your messy bun",
          imageLabel: "EXHIBIT A",
          afterLines: ["See?", "Exactly this.", "Messy.", "Cute.", "Completely you.", "And yes...", "I still really like it.", "❤️"],
          action: "OKAY, THAT'S ENOUGH PROOF →",
        },
        {
          visualType: "lines",
          lines: [
            "Some things are easy to explain.",
            "Some aren't.",
            "I just know that every time I see one of those messy buns...",
            "I notice.",
            "And I smile.",
            "That's it.",
            "That's the thing.",
            "Your wonderfully messy little buns.",
            "❤️",
          ],
          action: "CONTINUE",
          isFinal: true,
        },
      ],
    },
  },

  {
    id: 6,
    cardTitle: "It Was Just a Little Thing",
    title: "It Was Just a Little Thing",
    type: "storyJourney",
    unlockAt: unlockTime(0, 14, 0),
    content: {
      eyebrow: "06",
      heading: "It Was Just a Little Thing",
      states: [
        {
          visualType: "festCard",
          lines: ["I've been thinking...", "You have this funny little habit.", "Things don't have to be big for you to care about them.", "But I think I really understood that one night in Delhi."],
          cardTitle: "DELHI",
          cardLoading: "MEMORY LOADING...",
          action: "TAKE ME TO DELHI →",
        },
        {
          visualType: "lines",
          lines: [
            "We were in Connaught Place.",
            "Before the movie, I bought you a few clutchers.",
            "Nothing crazy.",
            "Just a few little things that I thought you'd like.",
            "And you did.",
            "Which, honestly, made buying them even more fun.",
            "Because obviously...",
            "you and clutchers.",
          ],
          action: "AND THEN WE WENT TO THE MOVIES →",
        },
        {
          visualType: "statusCheck",
          lines: ["Movie done.", "Time to head back to the hotel.", "And then...", "Wait.", "We'd left the clutchers at the theatre.", "All of them.", "And you were genuinely sad."],
          items: [
            { label: "CONNAUGHT PLACE", ok: true },
            { label: "MOVIE", ok: true },
            { label: "CLUTCHERS", ok: false },
          ],
          punchLine: "OH NO.",
          action: "I REMEMBER THAT PART →",
        },
        {
          visualType: "lines",
          lines: [
            "I remember you being genuinely upset about it.",
            "And I remember thinking...",
            "It's just a few clutchers.",
            "But then I realised...",
            "Maybe it wasn't really about the clutchers.",
            "It was because I had bought them for you.",
            "That was the part that mattered.",
            "And honestly...",
            "I thought that was really sweet.",
          ],
          action: "SO I DID SOMETHING ABOUT IT →",
        },
        {
          visualType: "lines",
          lines: [
            "The next morning, before leaving...",
            "I bought you another clutcher.",
            "Simple solution.",
            "Lost one?",
            "Get another one.",
            "But I think I was smiling about something else.",
            "Because somewhere between buying that replacement...",
            "I realised something about you.",
          ],
          action: "WHAT DID I REALISE? →",
        },
        {
          visualType: "lines",
          lines: [
            "You care about the little things.",
            "Even the really small ones.",
            "Especially when they come from me.",
            "And I don't think you realise how much I like that.",
            "Because when I give you something...",
            "It doesn't have to be expensive.",
            "It doesn't have to be impressive.",
            "It doesn't have to be some huge surprise.",
            "You'll still care.",
            "And somehow...",
            "that makes the smallest things feel important.",
            "That little clutcher was never really the point.",
            "You being sad about losing it...",
            "and me buying another one the next morning...",
            "that's the part I remember.",
          ],
          action: "ONE LAST THING →",
        },
        {
          visualType: "lines",
          lines: [
            "I think that's one of the things I love about you.",
            "You make little gestures feel like they matter.",
            "A tiny thing from me...",
            "can somehow become something you'll genuinely care about.",
            "And I don't think I'll ever take that for granted.",
            "So yes.",
            "Technically...",
            "I bought you another clutcher.",
            "But I think what I really took away from that trip...",
            "was something much smaller.",
            "And much sweeter.",
            "You care about the little things I give you.",
            "Because they came from me.",
            "❤️",
          ],
          action: "CONTINUE",
          isFinal: true,
        },
      ],
    },
  },

  {
    id: 7,
    cardTitle: "Go On, I'm Listening",
    title: "Go On, I'm Listening",
    type: "storyJourney",
    unlockAt: unlockTime(0, 14, 40),
    content: {
      eyebrow: "07",
      heading: "Go On, I'm Listening",
      states: [
        {
          visualType: "lines",
          lines: ["There is something I could probably listen to you do forever."],
          action: "WHAT? 👀",
        },
        {
          visualType: "lines",
          lines: [
            "Tell me a story.",
            "Actually...",
            "Tell me some gossip.",
            "Because somehow, when it's you telling it, even the smallest thing becomes an entire production.",
          ],
          action: "SHOW ME →",
        },
        {
          visualType: "fragments",
          lines: ["You never just tell a story.", "You tell it with your whole body."],
          fragments: ["HANDS", "EXPRESSIONS", "DRAMATIC REENACTMENT", "DIFFERENT VOICES", "FULL BACKSTORY"],
          afterLines: ["And somehow...", "I get the full director's cut."],
          action: "AND THEN IT GETS BETTER →",
        },
        {
          visualType: "lines",
          badge: "GOSSIP LOADING...",
          lines: [
            "The best part is when it's gossip.",
            "You explain EVERYTHING.",
            "Who said what.",
            "What happened before that.",
            "Why that thing mattered.",
            "What someone's face looked like.",
            "How you reacted.",
            "And obviously...",
            "I need the entire backstory before we're allowed to reach the actual point.",
            "And honestly?",
            "I love it.",
          ],
          action: "THE FUNNY PART →",
        },
        {
          visualType: "lines",
          lines: [
            "Half the time, I don't even remember what the story was actually about.",
            "Because somewhere along the way...",
            "I've stopped caring about the story.",
            "I'm just listening to you tell it.",
            "Watching you get animated.",
            "Watching your expressions change.",
            "Listening to you explain some tiny detail like it is the most important thing that has ever happened.",
            "And somehow...",
            "It is.",
          ],
          action: "THAT'S WHY →",
        },
        {
          visualType: "lines",
          lines: [
            "I think that's what I really like.",
            "Not the gossip.",
            "Not even necessarily the story.",
            "I just really enjoy listening to you.",
            "Because when you're excited about something...",
            "you make me want to hear every single detail.",
            "And I could probably sit there listening to you explain the same story...",
            "...with all six expressions...",
            "...all the hand movements...",
            "...and all the unnecessary details...",
            "and still ask:",
            "Okay, but what happened next?",
            "❤️",
          ],
          action: "KEEP TALKING →",
        },
        {
          visualType: "lines",
          lines: ["Okay.", "Now tell me what happened next.", "❤️"],
          action: "CONTINUE",
          isFinal: true,
        },
      ],
    },
  },

  {
    id: 8,
    cardTitle: "Little Bebu Things",
    title: "Little Bebu Things",
    type: "reveal",
    unlockAt: unlockTime(0, 15, 20),
    content: {
      eyebrow: "08",
      heading: "Little Bebu Things",
      teaser: "There are a few things about you that I don't think you realise I notice.",
      steps: [
        { label: "ONE", reveal: "You're unbearably cute when you talk in your sleep — or half-asleep." },
        { label: "ANOTHER", reveal: "You randomly start dancing the second you're happy or excited." },
        { label: "WAIT…", reveal: "You have basically claimed every jacket and hoodie I own at this point." },
      ],
      payoffLabel: "This is you",
      payoff: {
        body: ["These are the tiny things that make you, you."],
      },
    },
  },

  {
    id: 9,
    cardTitle: "You Were There",
    title: "You Were There",
    type: "reveal",
    unlockAt: unlockTime(0, 16, 0),
    content: {
      eyebrow: "09",
      heading: "You Were There",
      teaser: "You probably don't realise how often you were there.",
      steps: [
        { label: "Continue", reveal: "Not always in the obvious moments." },
        { label: "Continue", reveal: "Sometimes just by being there." },
      ],
      payoffLabel: "Show me",
      payoff: {
        body: [
          "You had your own tests going on, and you still showed up for every single one of my interviews.",
          "Before my first one, you ironed my shirt, brought me dahi-cheeni for luck, and wished me well — and somehow you remembered the details of that test better than I did.",
          "Whenever I'm upset about something, you drop everything else just to make me feel better. Every single time.",
        ],
      },
    },
  },

  {
    id: 10,
    cardTitle: "Our First Proper Date",
    title: "Our First Proper Date",
    type: "reveal",
    unlockAt: unlockTime(0, 16, 40),
    content: {
      eyebrow: "10",
      heading: "Our First Proper Date",
      teaser: "We had already made memories before this.",
      steps: [
        { label: "Continue", reveal: "But this one felt different." },
        { label: "Continue", reveal: "Because this was our first proper date." },
      ],
      payoffLabel: "Bean Me Up, Goa",
      payoff: {
        image: "assets/images/first date bean me up.jpg",
        alt: "Bean Me Up, Goa",
        body: [
          "Bean Me Up, Goa — our first real date. Candlelight, and you in that black dress I still think about. We'd already eaten together a hundred times before — campus, Ashok Redi, wherever — but this was the first time it actually felt like a date.",
          "Afterwards, back at the hotel, I realized I'd left my wallet behind. You panicked more than I did. We went back, the place was already closed, and somehow we still got it back — you were scared the entire way there that it was gone for good.",
        ],
      },
    },
  },

  {
    id: 11,
    cardTitle: "Go Downstairs 👀",
    title: "Go Downstairs 👀",
    type: "delivery",
    manualUnlock: true,
    content: {
      stageA: {
        lines: ["I know one thing you love a little too much. 👀", "Go downstairs."],
        buttonLabel: "I'M GOING 👀",
      },
      stageB: {
        lines: ["Something is waiting for you.", "Go get it. ❤️"],
        prompt: "Did you get it?",
        buttonLabel: "I GOT IT ❤️",
      },
      stageC: {
        lines: ["Good.", "Now enjoy. ❤️"],
      },
    },
  },

  {
    id: 12,
    cardTitle: "Nainital",
    title: "Nainital",
    type: "storyJourney",
    unlockAt: unlockTime(0, 17, 20),
    content: {
      eyebrow: "12",
      heading: "Nainital",
      states: [
        {
          visualType: "festCard",
          lines: ["This was our first trip with friends after you confessed.", "Right after we'd finished working together at the fest."],
          cardTitle: "NAINITAL",
          cardLoading: "MEMORY LOADING...",
          action: "TAKE ME THERE →",
        },
        {
          visualType: "lines",
          lines: [
            "I was terrified that once the fest ended, you'd get busy.",
            "And I wouldn't see you again until some other club thing came up.",
            "So this trip mattered to me more than I let on.",
          ],
          action: "BUT GETTING THERE WAS ITS OWN STORY →",
        },
        {
          visualType: "fragments",
          lines: ["Planning it was chaos."],
          fragments: ["NOBODY AGREED ON A LOCATION", "THE AIRBNB VS HOTEL ARGUMENT", "YOU LEFT THE GROUP ENTIRELY"],
          afterLines: ["I genuinely thought the trip might fall apart.", "So I messaged everyone individually just to hold it together."],
          action: "SOMEHOW, WE MADE IT →",
        },
        {
          visualType: "photo",
          lines: ["We made it.", "Eventually."],
          image: "assets/images/NANITAL TRIP.jpg",
          imageAlt: "Nainital",
          imageLabel: "NAINITAL",
          afterLines: ["And once we were there...", "you became my scooty partner."],
          action: "TELL YOU ABOUT THE SCOOTY RIDES →",
        },
        {
          visualType: "lines",
          lines: [
            "We rode slower than everyone else.",
            "Always ended up at the back of the three scooties.",
            "Which just meant more time.",
            "Just us.",
          ],
          action: "AND NO ONE KNEW YET →",
        },
        {
          visualType: "lines",
          lines: [
            "Nobody else knew we'd started seeing each other.",
            "You'd confessed right before the trip, after all the planning was already done.",
            "That first day, you drank for the first time — because you felt safe with me.",
            "And then you confessed in front of everyone.",
            "Not caring what anyone thought.",
            "That moment did a lot for us.",
          ],
          action: "THEN CAME THE REST OF THE TRIP →",
        },
        {
          visualType: "lines",
          lines: [
            "We were both slow walkers.",
            "So naturally, we got left behind.",
            "Reached the BNB almost an hour late.",
            "A dog somehow ended up showing us the way.",
          ],
          action: "AND THEN THE BUNNY EARS →",
        },
        {
          visualType: "photo",
          lines: ["You got way too excited about a winter cap with bunny ears.", "The kind that moved when you pulled them."],
          image: "assets/images/BUNNY.jpg",
          imageAlt: "The bunny-ear winter cap",
          imageLabel: "EXHIBIT: BUNNY EARS",
          afterLines: [
            "And we bought matching keychains.",
            "Somewhere in all that chaos...",
            "this became one of my favourite trips.",
            "❤️",
          ],
          action: "CONTINUE",
          isFinal: true,
        },
      ],
    },
  },

  {
    id: 13,
    cardTitle: "A Year of Us",
    title: "A Year of Us — Photo Diary",
    type: "diary",
    unlockAt: unlockTime(0, 18, 0),
    content: {
      heading: "A Year of Us — Photo Diary",
      subheading: "About a year and a half of us, since April 9, 2025 — in pictures.",
      entries: [
        {
          image: "assets/images/FIRST gARBA NIGHT.jpg",
          alt: "First Garba night",
          caption:
            "Our first campus Garba, during Navratri. The first attempt at getting a lift there failed completely — we made it eventually.",
        },
        {
          image:
            "assets/images/OUR FIRST LANAGR TOGETEHR- YOU WERE THE RESAON I WENT TO SO MANY PALCES FOR THE FIRST TIME IN MY COLLEGE LIFE.jpg",
          alt: "Our first langar together",
          caption:
            "The campus langar you took me to — the reason I started exploring so many new places on campus for the first time.",
        },
        {
          image: "assets/images/OUR FIRST N20.jpg",
          alt: "Our first N20",
          caption: "Our first comic show together on campus, during the fest.",
        },
        {
          image: "assets/images/FIRST PROM.HEIC",
          alt: "First prom",
          caption: "Our first prom, together.",
        },
        {
          image: "assets/images/OUR FIRST PHOTO IN FORMALS.jpg",
          alt: "First photo in formals",
          caption: "Our first photo in formals.",
        },
        {
          image: "assets/images/oUR FIRST PHOTO IN YOU WEARING SAREE - I COULDNT LIFT MY EYES OFF.JPG",
          alt: "First saree photo",
          caption: "The first time I saw you in a saree. I couldn't lift my eyes off.",
        },
        {
          image: "assets/images/OUR FIRST BEACH TOGEHTER.jpg",
          alt: "Our first beach together",
          caption: "Our first beach, together.",
        },
        {
          image: "assets/images/OUR FIRST CONCERT TOGETHER.jpg",
          alt: "Our first concert together",
          caption: "Our first concert, together.",
        },
        {
          image: "assets/images/OUR FIRST MOVIE IN THEATER.jpg",
          alt: "Our first movie in a theatre",
          caption: "Our first movie in a theatre.",
        },
        {
          image: "assets/images/FIRST PAHARI MANDIR TRIP.jpg",
          alt: "First Pahari Mandir trip",
          caption: "Our first Pahari Mandir trip.",
        },
        {
          image: "assets/images/NANITAL TRIP.jpg",
          alt: "Nainital",
          caption: "Nainital. (The full story gets its own chapter.)",
        },
        {
          image: "assets/images/MY FAVOURITE PHOTO OF YOU.jpg",
          alt: "My favourite photo of you",
          caption: "My favourite photo of you.",
        },
      ],
    },
  },

  {
    id: 14,
    cardTitle: "The Song We Still Remember",
    title: "The Song We Still Remember",
    type: "song",
    unlockAt: unlockTime(0, 18, 40),
    content: {
      eyebrow: "14",
      heading: "The Song We Still Remember",
      preLines: ["Some songs stay songs.", "And some become memories."],
      lostVideoTop: "VIDEO: LOST",
      lostVideoBottom: "MEMORY: VERY MUCH ALIVE",
      note:
        "This one doesn't need a big story. Some songs just remind you of someone the second they start playing. This is one of those, for me.",
      label: "SONG",
      title: "Aye Udi Udi Udi",
      src: "assets/audio/aye_udi_udi.mp3",
      postLine: "Still remember?",
    },
  },

  {
    id: 15,
    cardTitle: "Yours If You Want It",
    title: "Yours If You Want It",
    type: "memoryCoupon",
    unlockAt: unlockTime(0, 19, 20),
    content: {
      eyebrow: "15",
      heading: "Yours If You Want It",
      body: [],
      coupons: [
        {
          preamble: [
            "A Little Something For You",
            "I wanted to give you something you can use whenever you want.",
            "One wish. No rules about what it has to be. No list to choose from. No expiry date.",
            "You decide. ❤️",
          ],
          code: "COUPON № 01",
          title: "ONE WISH",
          description: "This coupon is good for one wish. Whatever you want. Whenever you want. Keep this coupon safe.",
          keepButtonLabel: "KEEP MY COUPON",
          keepMessage: "It's yours. ❤️",
          keepSubtext: ["Keep it safe.", "Whenever you're ready, send me this coupon along with your wish."],
        },
      ],
    },
  },

  {
    id: 16,
    cardTitle: "For Your 21st Year",
    title: "For Your 21st Year",
    type: "letter",
    unlockAt: unlockTime(0, 20, 0),
    content: {
      heading: "For Your 21st Year",
      paragraphs: [
        "I hope twenty-one is loud in all the right ways — new places, new people, new things you didn't expect to be good at.",
        "I hope you stay this confident, this sure of yourself, even on the days it's harder to be.",
        "I hope there's more peace than chaos this year, and when there's chaos, I hope you're laughing through most of it.",
        "Mostly, I just hope you have a genuinely good year — new memories, a little more growth, a little more fun, and a career you end up proud to talk about.",
      ],
      signOff: "Happy 21st.\nChaitu",
    },
  },

  {
    id: 17,
    cardTitle: "For Us",
    title: "For Us",
    type: "tiles",
    unlockAt: unlockTime(0, 20, 40),
    content: {
      eyebrow: "17",
      heading: "For Us",
      intro: "A few things I can already imagine us doing:",
      tiles: [
        "Seeing the world, one place at a time.",
        "Careers we're actually proud of.",
        "A mountain trip, just the two of us.",
        "A small house that's really ours.",
        "Fancy cutlery we probably won't use enough.",
        "Putting in the effort, always.",
        "Being there for each other, no matter what.",
        "Building an actual life together.",
        "All the ordinary, unremarkable, perfect everyday moments.",
      ],
    },
  },

  {
    id: 18,
    cardTitle: "Someday",
    title: "Someday",
    type: "message",
    unlockAt: unlockTime(0, 21, 20),
    content: {
      heading: "Someday",
      atmosphere: true,
      body: [
        "I don't know exactly what everything will look like.",
        "But I know I want to find out with you.",
      ],
    },
  },

  {
    id: 19,
    cardTitle: "My Girl ❤️",
    title: "My Girl ❤️",
    type: "storyJourney",
    unlockAt: unlockTime(0, 22, 0),
    content: {
      eyebrow: "19",
      heading: "My Girl ❤️",
      states: [
        {
          visualType: "lines",
          lines: ["Let me tell you something about my girl.", "It's a small story.", "But it says a lot."],
          action: "TELL ME →",
        },
        {
          visualType: "statusCheck",
          lines: ["We went out to eat.", "We ordered pure veg."],
          items: [
            { label: "ORDERED: PURE VEG", ok: true },
            { label: "RECEIVED: NON-VEG", ok: false },
          ],
          punchLine: "MIX-UP.",
          action: "AND THEN IT GOT WORSE →",
        },
        {
          visualType: "lines",
          lines: ["And the woman at the counter decided to get rude about it."],
          action: "BUT YOU DIDN'T BACK DOWN →",
        },
        {
          visualType: "lines",
          lines: ["You didn't let that slide for a second.", "You fought that whole battle.", "For both of us.", "While I just sat there..."],
          action: "QUIETLY THINKING →",
        },
        {
          visualType: "lines",
          lines: [{ text: "I have a girl who'll do everything for me.", emphasis: true }, "❤️"],
          action: "CONTINUE",
          isFinal: true,
        },
      ],
    },
  },

  {
    id: 20,
    cardTitle: "Before I Finish",
    title: "Before I Finish",
    type: "memoryCoupon",
    unlockAt: unlockTime(0, 22, 30),
    content: {
      eyebrow: "20",
      heading: "Before I Finish",
      body: ["Before you finish this,", "there's one more thing I want you to hear."],
      coupons: [
        {
          preamble: [
            "Okay...",
            "You thought you only got one?",
            "Maybe one wish wasn't enough.",
            "So I thought about it. And decided you get one more.",
          ],
          code: "COUPON № 02",
          title: "ONE MORE WISH",
          description: "One more wish. Whatever you want. Whenever you want. No expiry date. Keep this coupon safe. ❤️",
          keepButtonLabel: "KEEP MY COUPON",
          keepMessage: "It's yours too. ❤️",
          keepSubtext: [
            "Keep your coupons safe.",
            "When you're ready, send me this coupon along with your wish.",
          ],
        },
      ],
      closingLines: ["You never know when you'll want to use them.", "👀❤️"],
    },
  },

  {
    id: 21,
    cardTitle: "One Last Thing ❤️",
    title: "One Last Thing ❤️",
    type: "final",
    unlockAt: unlockTime(0, 23, 0),
    content: {
      lockedLine: "LOCKED",
      openingLines: [
        "You've collected the memories.",
        "The little things.",
        "The wishes.",
        "And everything in between.",
        "There's only one thing left.",
      ],
      anticipationLines: ["One Last Thing ❤️"],
      afterClickLine: "",
      playButtonLabel: "One Last Thing",
      finalAudio: "assets/audio/audio 2 last chapter.mp3",
      closingLines: ["Happy 21st, Bebu. ❤️", "Thank you for being you."],
    },
  },
];
